version: '3.4'

services:
  currencyratemonitor:
    image: ${DOCKER_REGISTRY-}currencyratemonitor
    container_name: currencyratemonitor
    environment:
        - TZ=Europe/Moscow
    build:
      context: .
      dockerfile: CurrencyRateMonitor/Dockerfile
    depends_on:
      currencyratemonitor.db:
        condition: service_started
  currencyratemonitor.db:
    image: postgres:latest
    container_name: currencyratemonitor.db
    environment:
      - POSTGRES_DB=currencyDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432