// <auto-generated />
using System;
using CurrencyRateMonitor.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurrencyRateMonitor.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20250307175107_CurrencyCodesNullable")]
    partial class CurrencyCodesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurrencyRateMonitor.Models.CurrencyCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CurrencyCodes");
                });

            modelBuilder.Entity("CurrencyRateMonitor.Models.CurrencyRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCodeCode")
                        .HasColumnType("text");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Nominal")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VunitRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCodeCode");

                    b.HasIndex("CurrencyId", "Date")
                        .IsUnique();

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("CurrencyRateMonitor.Models.CurrencyRate", b =>
                {
                    b.HasOne("CurrencyRateMonitor.Models.CurrencyCode", null)
                        .WithMany("Rates")
                        .HasForeignKey("CurrencyCodeCode");
                });

            modelBuilder.Entity("CurrencyRateMonitor.Models.CurrencyCode", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
